# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        synthetic: true
    #AppBundle\Services\JwtAuth: ['@doctrine.orm.entity_manager'] 
    app.jwtauth:
        class: AppBundle\Services\JwtAuth
        arguments: ['@doctrine.orm.entity_manager']
        public: true
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.helpers:
        class: AppBundle\Services\Helpers
        arguments: ["null"]
        public: true #Funciona aunque no este declarado

