#rutas de ApiBundle
user_login:
    path:   /user
    defaults:   { _controller: ApiBundle:ApiUser:loginApi}
    methods:    POST

prueba:
    path:   /default/{id}
    defaults: { _controller: ApiBundle:Default:prueba}
    methods:  GET

api_edit:
    path:   /posts/{id}
    defaults:   { _controller: ApiBundle:ApiPost:savePost}
    methods:    PUT

api_new:
    path:   /posts
    defaults:   { _controller: ApiBundle:ApiPost:savePost}
    methods:    POST

api-delete:
    path:   /posts/{id}
    defaults:   { _controller: ApiBundle:ApiPost:deletePost}
    methods:    DELETE


api_post:
    path:   /posts/{id}
    defaults: { _controller: ApiBundle:ApiPost:showPost}
    methods:  GET
